<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-A7D4RAN" failures="2" tests="10" name="Surefire test" time="53.727" errors="0" timestamp="2025-07-15T10:30:56 IST">
  <testcase classname="api.test.DDTests" name="testPostUser" time="7.048"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="2.249"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="2.256"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByname" time="6.898"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByname" time="1.231"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByname" time="3.395"/>
  <testcase classname="api.test.UserTests" name="testPostUser" time="1.307"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="16.16">
    <failure type="java.lang.AssertionError" message="User not found after retrying. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: User not found after retrying. expected [200] but found [404]
at api.test.UserTests.testGetUserByName(UserTests.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="3.43">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testUpdateUserByName(UserTests.java:136)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUserByName -->
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="2.373"/>
</testsuite> <!-- Surefire test -->
